### ISSUE TITLE
3D 配准时的label图像是如何得到的？

### ISSUE THREAD

**Issue by dragon-king-creater** [xzluo97/Diffeomorphic-demons#1]
您好，我是刚入门图像配准这个领域，有幸看到了您的项目，已经从ADNI下载了下载了核磁图像数据集，但是没有找到标签图像，希望得到您的回复

**Comment by xzluo97** [comment]
您好, 我记得ADNI数据是有label图像的.

 

Best regards,

 

罗鑫喆/Xinzhe Luo,

Postgraduate,

School of Data Science,

Fudan University

 

From: noreply@github.com <noreply@github.com> On Behalf Of Dragon Wang
Sent: 22 October 2020 17:04
To: xzluo97/Diffeomorphic-demons <Diffeomorphic-demons@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [xzluo97/Diffeomorphic-demons] 3D 配准时的label图像是如何得到的？ (#1)

 

您好，我是刚入门图像配准这个领域，有幸看到了您的项目，已经从ADNI下载了下载了核磁图像数据集，但是没有找到标签图像，希望得到您的回复
